# Generated by Django 5.2.4 on 2025-07-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
        migrations.AlterField(
            model_name='artwork',
            name='tag',
            field=models.CharField(choices=[('Mandala', 'Mandala'), ('Strippling(Dotted)', 'Strippling(Dotted)'), ('Oil Pastel', 'Oil Pastel'), ('Other', 'Other')], max_length=50),
        ),
    ]
