# Generated by Django 5.2.4 on 2025-07-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0002_remove_artwork_created_at_remove_artwork_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='tag',
            field=models.CharField(choices=[('Mandala', 'Mandala'), ('Strippling(Dotted)', 'Strippling(Dotted)'), ('Oil Pastel', 'Oil Pastel'), ('Color', 'Color'), ('Other', 'Other')], max_length=50),
        ),
    ]
